//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabi.Shared.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_nl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_nl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tabi.Shared.Resx.AppResources.nl", typeof(AppResources_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string ActivityOverviewPageTitle {
            get {
                return ResourceManager.GetString("ActivityOverviewPageTitle", resourceCulture);
            }
        }
        
        internal static string DayMapPageTitle {
            get {
                return ResourceManager.GetString("DayMapPageTitle", resourceCulture);
            }
        }
        
        internal static string TrackingSectionLabel {
            get {
                return ResourceManager.GetString("TrackingSectionLabel", resourceCulture);
            }
        }
        
        internal static string TrackingSwitchLabel {
            get {
                return ResourceManager.GetString("TrackingSwitchLabel", resourceCulture);
            }
        }
        
        internal static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        internal static string AboutSectionLabel {
            get {
                return ResourceManager.GetString("AboutSectionLabel", resourceCulture);
            }
        }
        
        internal static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        internal static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        internal static string ServiceText {
            get {
                return ResourceManager.GetString("ServiceText", resourceCulture);
            }
        }
        
        internal static string OpenFileInApp {
            get {
                return ResourceManager.GetString("OpenFileInApp", resourceCulture);
            }
        }
        
        internal static string TrackingExplanation {
            get {
                return ResourceManager.GetString("TrackingExplanation", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        internal static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        internal static string IntroWelcomeTitle {
            get {
                return ResourceManager.GetString("IntroWelcomeTitle", resourceCulture);
            }
        }
        
        internal static string IntroWelcomeText {
            get {
                return ResourceManager.GetString("IntroWelcomeText", resourceCulture);
            }
        }
        
        internal static string ErrorOccurredTitle {
            get {
                return ResourceManager.GetString("ErrorOccurredTitle", resourceCulture);
            }
        }
        
        internal static string LoginFailureTitle {
            get {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }
        
        internal static string LoginFailureText {
            get {
                return ResourceManager.GetString("LoginFailureText", resourceCulture);
            }
        }
        
        internal static string LoginIntroTitle {
            get {
                return ResourceManager.GetString("LoginIntroTitle", resourceCulture);
            }
        }
        
        internal static string LoginIntroText {
            get {
                return ResourceManager.GetString("LoginIntroText", resourceCulture);
            }
        }
        
        internal static string LocationPermissionButton {
            get {
                return ResourceManager.GetString("LocationPermissionButton", resourceCulture);
            }
        }
        
        internal static string LocationPermissionTitle {
            get {
                return ResourceManager.GetString("LocationPermissionTitle", resourceCulture);
            }
        }
        
        internal static string LocationPermissionText {
            get {
                return ResourceManager.GetString("LocationPermissionText", resourceCulture);
            }
        }
        
        internal static string UploadDataLabel {
            get {
                return ResourceManager.GetString("UploadDataLabel", resourceCulture);
            }
        }
        
        internal static string UploadDataButton {
            get {
                return ResourceManager.GetString("UploadDataButton", resourceCulture);
            }
        }
        
        internal static string LocationPermissionRationaleTitle {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleTitle", resourceCulture);
            }
        }
        
        internal static string LocationPermissionRationaleText {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleText", resourceCulture);
            }
        }
        
        internal static string LocationPermissionDeniedOpenSettingsiOSTitle {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSTitle", resourceCulture);
            }
        }
        
        internal static string LocationPermissionDeniedOpenSettingsiOSText {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSText", resourceCulture);
            }
        }
        
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        internal static string NoInternetConnectionTitle {
            get {
                return ResourceManager.GetString("NoInternetConnectionTitle", resourceCulture);
            }
        }
        
        internal static string NoInternetConnectionText {
            get {
                return ResourceManager.GetString("NoInternetConnectionText", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string MobileDataUsageTitle {
            get {
                return ResourceManager.GetString("MobileDataUsageTitle", resourceCulture);
            }
        }
        
        internal static string MobileDataUsageText {
            get {
                return ResourceManager.GetString("MobileDataUsageText", resourceCulture);
            }
        }
        
        internal static string UploadDataErrorText {
            get {
                return ResourceManager.GetString("UploadDataErrorText", resourceCulture);
            }
        }
        
        internal static string UploadDataInProgress {
            get {
                return ResourceManager.GetString("UploadDataInProgress", resourceCulture);
            }
        }
        
        internal static string DataUploadSuccesful {
            get {
                return ResourceManager.GetString("DataUploadSuccesful", resourceCulture);
            }
        }
        
        internal static string DaySelectorButton {
            get {
                return ResourceManager.GetString("DaySelectorButton", resourceCulture);
            }
        }
        
        internal static string TrackDetailPageTitle {
            get {
                return ResourceManager.GetString("TrackDetailPageTitle", resourceCulture);
            }
        }
        
        internal static string InformationSectionLabel {
            get {
                return ResourceManager.GetString("InformationSectionLabel", resourceCulture);
            }
        }
        
        internal static string TripDataSectionLabel {
            get {
                return ResourceManager.GetString("TripDataSectionLabel", resourceCulture);
            }
        }
        
        internal static string TransportModeLabel {
            get {
                return ResourceManager.GetString("TransportModeLabel", resourceCulture);
            }
        }
        
        internal static string SelectTransportModeButton {
            get {
                return ResourceManager.GetString("SelectTransportModeButton", resourceCulture);
            }
        }
        
        internal static string TransportModeSelectionExplanation {
            get {
                return ResourceManager.GetString("TransportModeSelectionExplanation", resourceCulture);
            }
        }
        
        internal static string BikeLabel {
            get {
                return ResourceManager.GetString("BikeLabel", resourceCulture);
            }
        }
        
        internal static string BusLabel {
            get {
                return ResourceManager.GetString("BusLabel", resourceCulture);
            }
        }
        
        internal static string CarLabel {
            get {
                return ResourceManager.GetString("CarLabel", resourceCulture);
            }
        }
        
        internal static string MobilityScooterLabel {
            get {
                return ResourceManager.GetString("MobilityScooterLabel", resourceCulture);
            }
        }
        
        internal static string RunLabel {
            get {
                return ResourceManager.GetString("RunLabel", resourceCulture);
            }
        }
        
        internal static string TramLabel {
            get {
                return ResourceManager.GetString("TramLabel", resourceCulture);
            }
        }
        
        internal static string WalkLabel {
            get {
                return ResourceManager.GetString("WalkLabel", resourceCulture);
            }
        }
        
        internal static string MopedLabel {
            get {
                return ResourceManager.GetString("MopedLabel", resourceCulture);
            }
        }
        
        internal static string MotorcycleLabel {
            get {
                return ResourceManager.GetString("MotorcycleLabel", resourceCulture);
            }
        }
        
        internal static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        internal static string ScooterLabel {
            get {
                return ResourceManager.GetString("ScooterLabel", resourceCulture);
            }
        }
        
        internal static string SubwayLabel {
            get {
                return ResourceManager.GetString("SubwayLabel", resourceCulture);
            }
        }
        
        internal static string TrainLabel {
            get {
                return ResourceManager.GetString("TrainLabel", resourceCulture);
            }
        }
        
        internal static string NoDataInOverview {
            get {
                return ResourceManager.GetString("NoDataInOverview", resourceCulture);
            }
        }
        
        internal static string DaySelectorPageTitle {
            get {
                return ResourceManager.GetString("DaySelectorPageTitle", resourceCulture);
            }
        }
        
        internal static string SensorPermissionButton {
            get {
                return ResourceManager.GetString("SensorPermissionButton", resourceCulture);
            }
        }
        
        internal static string SensorPermissionDeniedOpenSettingsiOSText {
            get {
                return ResourceManager.GetString("SensorPermissionDeniedOpenSettingsiOSText", resourceCulture);
            }
        }
        
        internal static string SensorPermissionDeniedOpenSettingsiOSTitle {
            get {
                return ResourceManager.GetString("SensorPermissionDeniedOpenSettingsiOSTitle", resourceCulture);
            }
        }
        
        internal static string SensorPermissionRationaleText {
            get {
                return ResourceManager.GetString("SensorPermissionRationaleText", resourceCulture);
            }
        }
        
        internal static string SensorPermissionRationaleTitle {
            get {
                return ResourceManager.GetString("SensorPermissionRationaleTitle", resourceCulture);
            }
        }
        
        internal static string ServiceNotificationChannelLabel {
            get {
                return ResourceManager.GetString("ServiceNotificationChannelLabel", resourceCulture);
            }
        }
        
        internal static string LoggingInWaitMessage {
            get {
                return ResourceManager.GetString("LoggingInWaitMessage", resourceCulture);
            }
        }
        
        internal static string WelcomeTitleLabel {
            get {
                return ResourceManager.GetString("WelcomeTitleLabel", resourceCulture);
            }
        }
        
        internal static string LocationTitleLabel {
            get {
                return ResourceManager.GetString("LocationTitleLabel", resourceCulture);
            }
        }
        
        internal static string LocationIntroLabel {
            get {
                return ResourceManager.GetString("LocationIntroLabel", resourceCulture);
            }
        }
        
        internal static string LocationSpecificiOSLabel {
            get {
                return ResourceManager.GetString("LocationSpecificiOSLabel", resourceCulture);
            }
        }
        
        internal static string LocationTryAgainLabel {
            get {
                return ResourceManager.GetString("LocationTryAgainLabel", resourceCulture);
            }
        }
        
        internal static string EnableLocationServices {
            get {
                return ResourceManager.GetString("EnableLocationServices", resourceCulture);
            }
        }
        
        internal static string LocationPermissionGiven {
            get {
                return ResourceManager.GetString("LocationPermissionGiven", resourceCulture);
            }
        }
        
        internal static string MotionTitleLabel {
            get {
                return ResourceManager.GetString("MotionTitleLabel", resourceCulture);
            }
        }
        
        internal static string MotionIntroLabel {
            get {
                return ResourceManager.GetString("MotionIntroLabel", resourceCulture);
            }
        }
        
        internal static string MotionPermissionButton {
            get {
                return ResourceManager.GetString("MotionPermissionButton", resourceCulture);
            }
        }
        
        internal static string ThanksTitleLabel {
            get {
                return ResourceManager.GetString("ThanksTitleLabel", resourceCulture);
            }
        }
        
        internal static string ThanksText {
            get {
                return ResourceManager.GetString("ThanksText", resourceCulture);
            }
        }
        
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string StopNameLabel {
            get {
                return ResourceManager.GetString("StopNameLabel", resourceCulture);
            }
        }
        
        internal static string StopMotiveLabel {
            get {
                return ResourceManager.GetString("StopMotiveLabel", resourceCulture);
            }
        }
        
        internal static string DeviceIdLabel {
            get {
                return ResourceManager.GetString("DeviceIdLabel", resourceCulture);
            }
        }
        
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        internal static string SetStopNameHint {
            get {
                return ResourceManager.GetString("SetStopNameHint", resourceCulture);
            }
        }
        
        internal static string SetStopMotiveHint {
            get {
                return ResourceManager.GetString("SetStopMotiveHint", resourceCulture);
            }
        }
        
        internal static string StopDetailPageExplanation {
            get {
                return ResourceManager.GetString("StopDetailPageExplanation", resourceCulture);
            }
        }
        
        internal static string StopMotivePageTitle {
            get {
                return ResourceManager.GetString("StopMotivePageTitle", resourceCulture);
            }
        }
        
        internal static string LoadingDataLabel {
            get {
                return ResourceManager.GetString("LoadingDataLabel", resourceCulture);
            }
        }
        
        internal static string APIUnavailableTitle {
            get {
                return ResourceManager.GetString("APIUnavailableTitle", resourceCulture);
            }
        }
        
        internal static string APIUnavailableText {
            get {
                return ResourceManager.GetString("APIUnavailableText", resourceCulture);
            }
        }
        
        internal static string ApiUrlLabel {
            get {
                return ResourceManager.GetString("ApiUrlLabel", resourceCulture);
            }
        }
        
        internal static string LastSyncLabel {
            get {
                return ResourceManager.GetString("LastSyncLabel", resourceCulture);
            }
        }
        
        internal static string TimeAgoLessThanAMinute {
            get {
                return ResourceManager.GetString("TimeAgoLessThanAMinute", resourceCulture);
            }
        }
        
        internal static string TimeAgoMinutes {
            get {
                return ResourceManager.GetString("TimeAgoMinutes", resourceCulture);
            }
        }
        
        internal static string TimeAgoMinute {
            get {
                return ResourceManager.GetString("TimeAgoMinute", resourceCulture);
            }
        }
        
        internal static string TimeAgoHours {
            get {
                return ResourceManager.GetString("TimeAgoHours", resourceCulture);
            }
        }
        
        internal static string TimeAgoHour {
            get {
                return ResourceManager.GetString("TimeAgoHour", resourceCulture);
            }
        }
        
        internal static string TimeAgoNever {
            get {
                return ResourceManager.GetString("TimeAgoNever", resourceCulture);
            }
        }
        
        internal static string PreviousDay {
            get {
                return ResourceManager.GetString("PreviousDay", resourceCulture);
            }
        }
        
        internal static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        internal static string TrackMotiveLabel {
            get {
                return ResourceManager.GetString("TrackMotiveLabel", resourceCulture);
            }
        }
        
        internal static string SetTrackMotiveHint {
            get {
                return ResourceManager.GetString("SetTrackMotiveHint", resourceCulture);
            }
        }
        
        internal static string TrackMotivePageTitle {
            get {
                return ResourceManager.GetString("TrackMotivePageTitle", resourceCulture);
            }
        }
        
        internal static string PossibleStopsSectionLabel {
            get {
                return ResourceManager.GetString("PossibleStopsSectionLabel", resourceCulture);
            }
        }
        
        internal static string ChangeAllStopNamesLabel {
            get {
                return ResourceManager.GetString("ChangeAllStopNamesLabel", resourceCulture);
            }
        }
        
        internal static string ReplaceWithExistingStopTitle {
            get {
                return ResourceManager.GetString("ReplaceWithExistingStopTitle", resourceCulture);
            }
        }
        
        internal static string ReplaceWithExistingStopText {
            get {
                return ResourceManager.GetString("ReplaceWithExistingStopText", resourceCulture);
            }
        }
        
        internal static string ReplaceWithExistingStopOkText {
            get {
                return ResourceManager.GetString("ReplaceWithExistingStopOkText", resourceCulture);
            }
        }
        
        internal static string StartPin {
            get {
                return ResourceManager.GetString("StartPin", resourceCulture);
            }
        }
        
        internal static string EndPin {
            get {
                return ResourceManager.GetString("EndPin", resourceCulture);
            }
        }
        
        internal static string UnsetStopName {
            get {
                return ResourceManager.GetString("UnsetStopName", resourceCulture);
            }
        }
        
        internal static string SkipTour {
            get {
                return ResourceManager.GetString("SkipTour", resourceCulture);
            }
        }
        
        internal static string NextTour {
            get {
                return ResourceManager.GetString("NextTour", resourceCulture);
            }
        }
        
        internal static string StopTourTitle {
            get {
                return ResourceManager.GetString("StopTourTitle", resourceCulture);
            }
        }
        
        internal static string StopTourText {
            get {
                return ResourceManager.GetString("StopTourText", resourceCulture);
            }
        }
        
        internal static string MotiveTourTitle {
            get {
                return ResourceManager.GetString("MotiveTourTitle", resourceCulture);
            }
        }
        
        internal static string MotiveTourText {
            get {
                return ResourceManager.GetString("MotiveTourText", resourceCulture);
            }
        }
        
        internal static string TransportModeTourTitle {
            get {
                return ResourceManager.GetString("TransportModeTourTitle", resourceCulture);
            }
        }
        
        internal static string TransportModeTourText {
            get {
                return ResourceManager.GetString("TransportModeTourText", resourceCulture);
            }
        }
        
        internal static string SettingsTourTitle {
            get {
                return ResourceManager.GetString("SettingsTourTitle", resourceCulture);
            }
        }
        
        internal static string SettingsTourText {
            get {
                return ResourceManager.GetString("SettingsTourText", resourceCulture);
            }
        }
        
        internal static string LangCode {
            get {
                return ResourceManager.GetString("LangCode", resourceCulture);
            }
        }
        
        internal static string ShowTour {
            get {
                return ResourceManager.GetString("ShowTour", resourceCulture);
            }
        }
    }
}
