//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabi.Shared.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabi.Shared.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSectionLabel {
            get {
                return ResourceManager.GetString("AboutSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ActivityOverviewPageTitle {
            get {
                return ResourceManager.GetString("ActivityOverviewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike.
        /// </summary>
        public static string BikeLabel {
            get {
                return ResourceManager.GetString("BikeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string BusLabel {
            get {
                return ResourceManager.GetString("BusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string CarLabel {
            get {
                return ResourceManager.GetString("CarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data upload succesful.
        /// </summary>
        public static string DataUploadSuccesful {
            get {
                return ResourceManager.GetString("DataUploadSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string DayMapPageTitle {
            get {
                return ResourceManager.GetString("DayMapPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string DaySelectorButton {
            get {
                return ResourceManager.GetString("DaySelectorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select day.
        /// </summary>
        public static string DaySelectorPageTitle {
            get {
                return ResourceManager.GetString("DaySelectorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorOccurredTitle {
            get {
                return ResourceManager.GetString("ErrorOccurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationSectionLabel {
            get {
                return ResourceManager.GetString("InformationSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Tabi Verplaatsingen app. You will need to login with your credentials on the next screen..
        /// </summary>
        public static string IntroWelcomeText {
            get {
                return ResourceManager.GetString("IntroWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabi.
        /// </summary>
        public static string IntroWelcomeTitle {
            get {
                return ResourceManager.GetString("IntroWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow location access.
        /// </summary>
        public static string LocationPermissionButton {
            get {
                return ResourceManager.GetString("LocationPermissionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change location permission to &quot;Always&quot; in the Settings..
        /// </summary>
        public static string LocationPermissionDeniedOpenSettingsiOSText {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LocationPermissionDeniedOpenSettingsiOSTitle {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission needs to be granted for the application to record your movements..
        /// </summary>
        public static string LocationPermissionRationaleText {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location required.
        /// </summary>
        public static string LocationPermissionRationaleTitle {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to give location access to the app so that we can use this to track your movements..
        /// </summary>
        public static string LocationPermissionText {
            get {
                return ResourceManager.GetString("LocationPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission required.
        /// </summary>
        public static string LocationPermissionTitle {
            get {
                return ResourceManager.GetString("LocationPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your username and password..
        /// </summary>
        public static string LoginFailureText {
            get {
                return ResourceManager.GetString("LoginFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        public static string LoginFailureTitle {
            get {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login with the provided username and password to continue..
        /// </summary>
        public static string LoginIntroText {
            get {
                return ResourceManager.GetString("LoginIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with credentials.
        /// </summary>
        public static string LoginIntroTitle {
            get {
                return ResourceManager.GetString("LoginIntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will use your mobile connection to upload data. This may result in fees from your mobile operator..
        /// </summary>
        public static string MobileDataUsageText {
            get {
                return ResourceManager.GetString("MobileDataUsageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Data.
        /// </summary>
        public static string MobileDataUsageTitle {
            get {
                return ResourceManager.GetString("MobileDataUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility Scooter.
        /// </summary>
        public static string MobilityScooterLabel {
            get {
                return ResourceManager.GetString("MobilityScooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moped.
        /// </summary>
        public static string MopedLabel {
            get {
                return ResourceManager.GetString("MopedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string MotorcycleLabel {
            get {
                return ResourceManager.GetString("MotorcycleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data available to show you. If this is today; wait a few minutes and pull to refresh the page..
        /// </summary>
        public static string NoDataInOverview {
            get {
                return ResourceManager.GetString("NoDataInOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabi could not connect to the internet.
        /// </summary>
        public static string NoInternetConnectionText {
            get {
                return ResourceManager.GetString("NoInternetConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        public static string NoInternetConnectionTitle {
            get {
                return ResourceManager.GetString("NoInternetConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiii:.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select app.
        /// </summary>
        public static string OpenFileInApp {
            get {
                return ResourceManager.GetString("OpenFileInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yourpassword.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunLabel {
            get {
                return ResourceManager.GetString("RunLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scooter.
        /// </summary>
        public static string ScooterLabel {
            get {
                return ResourceManager.GetString("ScooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select transport modes.
        /// </summary>
        public static string SelectTransportModeButton {
            get {
                return ResourceManager.GetString("SelectTransportModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion and Fitness permission required.
        /// </summary>
        public static string SensorPermissionButton {
            get {
                return ResourceManager.GetString("SensorPermissionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Motion and Fitness permission on in the Settings..
        /// </summary>
        public static string SensorPermissionDeniedOpenSettingsiOSText {
            get {
                return ResourceManager.GetString("SensorPermissionDeniedOpenSettingsiOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SensorPermissionDeniedOpenSettingsiOSTitle {
            get {
                return ResourceManager.GetString("SensorPermissionDeniedOpenSettingsiOSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion and Fitness permission needs to be granted for the application to record your movements..
        /// </summary>
        public static string SensorPermissionRationaleText {
            get {
                return ResourceManager.GetString("SensorPermissionRationaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion and Fitness required.
        /// </summary>
        public static string SensorPermissionRationaleTitle {
            get {
                return ResourceManager.GetString("SensorPermissionRationaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in the background to track your movement..
        /// </summary>
        public static string ServiceText {
            get {
                return ResourceManager.GetString("ServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabi.
        /// </summary>
        public static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subway.
        /// </summary>
        public static string SubwayLabel {
            get {
                return ResourceManager.GetString("SubwayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string TrackDetailPageTitle {
            get {
                return ResourceManager.GetString("TrackDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s possible to disable the collection of data by disabling the tracking below..
        /// </summary>
        public static string TrackingExplanation {
            get {
                return ResourceManager.GetString("TrackingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection.
        /// </summary>
        public static string TrackingSectionLabel {
            get {
                return ResourceManager.GetString("TrackingSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string TrackingSwitchLabel {
            get {
                return ResourceManager.GetString("TrackingSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string TrainLabel {
            get {
                return ResourceManager.GetString("TrainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram.
        /// </summary>
        public static string TramLabel {
            get {
                return ResourceManager.GetString("TramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport modes.
        /// </summary>
        public static string TransportModeLabel {
            get {
                return ResourceManager.GetString("TransportModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the button above to fill in the transport mode(s) used during the trip currently on display. You can select multiple transport modes. .
        /// </summary>
        public static string TransportModeSelectionExplanation {
            get {
                return ResourceManager.GetString("TransportModeSelectionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip data.
        /// </summary>
        public static string TripDataSectionLabel {
            get {
                return ResourceManager.GetString("TripDataSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data.
        /// </summary>
        public static string UploadDataButton {
            get {
                return ResourceManager.GetString("UploadDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload data. If this problem keeps occuring please contact support..
        /// </summary>
        public static string UploadDataErrorText {
            get {
                return ResourceManager.GetString("UploadDataErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data....
        /// </summary>
        public static string UploadDataInProgress {
            get {
                return ResourceManager.GetString("UploadDataInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string UploadDataLabel {
            get {
                return ResourceManager.GetString("UploadDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JaneDoe.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk.
        /// </summary>
        public static string WalkLabel {
            get {
                return ResourceManager.GetString("WalkLabel", resourceCulture);
            }
        }
    }
}
