//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabi.Shared.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tabi.Shared.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        public static string ActivityOverviewPageTitle {
            get {
                return ResourceManager.GetString("ActivityOverviewPageTitle", resourceCulture);
            }
        }
        
        public static string DayMapPageTitle {
            get {
                return ResourceManager.GetString("DayMapPageTitle", resourceCulture);
            }
        }
        
        public static string TrackingSectionLabel {
            get {
                return ResourceManager.GetString("TrackingSectionLabel", resourceCulture);
            }
        }
        
        public static string TrackingSwitchLabel {
            get {
                return ResourceManager.GetString("TrackingSwitchLabel", resourceCulture);
            }
        }
        
        public static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        public static string AboutSectionLabel {
            get {
                return ResourceManager.GetString("AboutSectionLabel", resourceCulture);
            }
        }
        
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        public static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        public static string ServiceText {
            get {
                return ResourceManager.GetString("ServiceText", resourceCulture);
            }
        }
        
        public static string OpenFileInApp {
            get {
                return ResourceManager.GetString("OpenFileInApp", resourceCulture);
            }
        }
        
        public static string TrackingExplanation {
            get {
                return ResourceManager.GetString("TrackingExplanation", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        public static string IntroWelcomeTitle {
            get {
                return ResourceManager.GetString("IntroWelcomeTitle", resourceCulture);
            }
        }
        
        public static string IntroWelcomeText {
            get {
                return ResourceManager.GetString("IntroWelcomeText", resourceCulture);
            }
        }
        
        public static string ErrorOccurredTitle {
            get {
                return ResourceManager.GetString("ErrorOccurredTitle", resourceCulture);
            }
        }
        
        public static string LoginFailureTitle {
            get {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }
        
        public static string LoginFailureText {
            get {
                return ResourceManager.GetString("LoginFailureText", resourceCulture);
            }
        }
        
        public static string LoginIntroTitle {
            get {
                return ResourceManager.GetString("LoginIntroTitle", resourceCulture);
            }
        }
        
        public static string LoginIntroText {
            get {
                return ResourceManager.GetString("LoginIntroText", resourceCulture);
            }
        }
        
        public static string LocationPermissionButton {
            get {
                return ResourceManager.GetString("LocationPermissionButton", resourceCulture);
            }
        }
        
        public static string LocationPermissionTitle {
            get {
                return ResourceManager.GetString("LocationPermissionTitle", resourceCulture);
            }
        }
        
        public static string LocationPermissionText {
            get {
                return ResourceManager.GetString("LocationPermissionText", resourceCulture);
            }
        }
        
        public static string UploadDataLabel {
            get {
                return ResourceManager.GetString("UploadDataLabel", resourceCulture);
            }
        }
        
        public static string UploadDataButton {
            get {
                return ResourceManager.GetString("UploadDataButton", resourceCulture);
            }
        }
        
        public static string LocationPermissionRationaleTitle {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleTitle", resourceCulture);
            }
        }
        
        public static string LocationPermissionRationaleText {
            get {
                return ResourceManager.GetString("LocationPermissionRationaleText", resourceCulture);
            }
        }
        
        public static string LocationPermissionDeniedOpenSettingsiOSTitle {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSTitle", resourceCulture);
            }
        }
        
        public static string LocationPermissionDeniedOpenSettingsiOSText {
            get {
                return ResourceManager.GetString("LocationPermissionDeniedOpenSettingsiOSText", resourceCulture);
            }
        }
        
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        public static string NoInternetConnectionTitle {
            get {
                return ResourceManager.GetString("NoInternetConnectionTitle", resourceCulture);
            }
        }
        
        public static string NoInternetConnectionText {
            get {
                return ResourceManager.GetString("NoInternetConnectionText", resourceCulture);
            }
        }
        
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        public static string MobileDataUsageTitle {
            get {
                return ResourceManager.GetString("MobileDataUsageTitle", resourceCulture);
            }
        }
        
        public static string MobileDataUsageText {
            get {
                return ResourceManager.GetString("MobileDataUsageText", resourceCulture);
            }
        }
        
        public static string UploadDataErrorText {
            get {
                return ResourceManager.GetString("UploadDataErrorText", resourceCulture);
            }
        }
        
        public static string UploadDataInProgress {
            get {
                return ResourceManager.GetString("UploadDataInProgress", resourceCulture);
            }
        }
        
        public static string DataUploadSuccesful {
            get {
                return ResourceManager.GetString("DataUploadSuccesful", resourceCulture);
            }
        }
        
        public static string DaySelectorButton {
            get {
                return ResourceManager.GetString("DaySelectorButton", resourceCulture);
            }
        }
        
        public static string TrackDetailPageTitle {
            get {
                return ResourceManager.GetString("TrackDetailPageTitle", resourceCulture);
            }
        }
        
        public static string InformationSectionLabel {
            get {
                return ResourceManager.GetString("InformationSectionLabel", resourceCulture);
            }
        }
        
        public static string TripDataSectionLabel {
            get {
                return ResourceManager.GetString("TripDataSectionLabel", resourceCulture);
            }
        }
        
        public static string TransportModeLabel {
            get {
                return ResourceManager.GetString("TransportModeLabel", resourceCulture);
            }
        }
        
        public static string SelectTransportModeButton {
            get {
                return ResourceManager.GetString("SelectTransportModeButton", resourceCulture);
            }
        }
        
        public static string TransportModeSelectionExplanation {
            get {
                return ResourceManager.GetString("TransportModeSelectionExplanation", resourceCulture);
            }
        }
        
        public static string BikeLabel {
            get {
                return ResourceManager.GetString("BikeLabel", resourceCulture);
            }
        }
        
        public static string BusLabel {
            get {
                return ResourceManager.GetString("BusLabel", resourceCulture);
            }
        }
        
        public static string CarLabel {
            get {
                return ResourceManager.GetString("CarLabel", resourceCulture);
            }
        }
        
        public static string MobilityScooterLabel {
            get {
                return ResourceManager.GetString("MobilityScooterLabel", resourceCulture);
            }
        }
        
        public static string RunLabel {
            get {
                return ResourceManager.GetString("RunLabel", resourceCulture);
            }
        }
        
        public static string TramLabel {
            get {
                return ResourceManager.GetString("TramLabel", resourceCulture);
            }
        }
        
        public static string WalkLabel {
            get {
                return ResourceManager.GetString("WalkLabel", resourceCulture);
            }
        }
        
        public static string MopedLabel {
            get {
                return ResourceManager.GetString("MopedLabel", resourceCulture);
            }
        }
        
        public static string MotorcycleLabel {
            get {
                return ResourceManager.GetString("MotorcycleLabel", resourceCulture);
            }
        }
        
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        public static string ScooterLabel {
            get {
                return ResourceManager.GetString("ScooterLabel", resourceCulture);
            }
        }
        
        public static string SubwayLabel {
            get {
                return ResourceManager.GetString("SubwayLabel", resourceCulture);
            }
        }
        
        public static string TrainLabel {
            get {
                return ResourceManager.GetString("TrainLabel", resourceCulture);
            }
        }
        
        public static string NoDataInOverview {
            get {
                return ResourceManager.GetString("NoDataInOverview", resourceCulture);
            }
        }
    }
}
